//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromoNoteEntities : DbContext
    {
        public PromoNoteEntities()
            : base("name=PromoNoteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user_auth> user_auth { get; set; }
        public virtual DbSet<promo_note_detail> promo_note_detail { get; set; }
        public virtual DbSet<promo_note_header> promo_note_header { get; set; }
    }
}
