//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_auth
    {
        public long id { get; set; }
        public string username { get; set; }
        public System.Guid password { get; set; }
        public string fullname { get; set; }
        public string tel { get; set; }
    }
}
